FROM node:20-alpine

# Рабочая директория внутри контейнера
WORKDIR /app

# Устанавливаем curl и libc6-compat для совместимости с Rollup
RUN apk add --no-cache curl libc6-compat

# Обновляем npm до последней версии
RUN npm install -g npm@latest

# Копируем package.json и lock файл
COPY package*.json ./

# Устанавливаем зависимости с принудительной установкой
RUN npm install --force

# Копируем исходный код
COPY . .

# Открываем порт Vite
EXPOSE 5173

# Запускаем dev-сервер
CMD ["npm", "run", "dev"] 